# Generated by Django 3.2.9 on 2022-03-09 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0003_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='firstName',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='lastName',
            new_name='lname',
        ),
    ]
