# Generated by Django 3.2.9 on 2022-03-11 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0005_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
