# Generated by Django 3.2.9 on 2022-03-15 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0006_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(max_length=10)),
                ('image', models.ImageField(blank='true', null='true', upload_to='product_images/')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workapp.signup')),
            ],
        ),
    ]
