# Generated by Django 3.2.9 on 2022-03-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0007_productdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apiusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
